export const SET_CURRENCIES = 'SET_CURRENCIES';
export const FETCH_CURRENCIES ='FETCH_CURRENCIES';
export const SET_LGS_COLUMNS = 'SET_LGS_COLUMNS';
export const FETCH_LGS_COLUMNS = 'FETCH_LGS_COLUMNS';
export const SET_SMS_COLUMNS = 'SET_SMS_COLUMNS';
export const FETCH_SMS_COLUMNS = 'FETCH_SMS_COLUMNS';
